### ISSUE TITLE
About the content of category

### ISSUE THREAD

**Issue by ares-huy-le** [2359media/MEDCategories#1]
Should we just add own category? or we can add some category from 3rd to it. Example: 
- We have some famous category like this: 
  - https://github.com/bennyguitar/Colours
  - https://github.com/khanlou/Objective-Shorthand
  - https://github.com/steipete/PSFoundation
 - ...

Do we need to have a way for collecting and reusing them?

**Comment by onmyway133** [comment]
Yep, I think we can collect some from other repos
